project:
  type: website
  output-dir: docs

website:
  title: "PCA Compression Homework"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brands
    css: styles.css
    toc: true

editor: visual

